#Created by webjeda - http://webjeda.com

# Site settings
title: "I'm DennyLao"
title-font-size: '4em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

email: szdenny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://szdenny.github.io" # the base hostname & protocol for your site

permalink: :title/

# Build settings
markdown: kramdown
highlight: rouge
paginate: 5
paginate_path: /page:num/


# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

#CSS
sass:
  style: compressed


include: [_pages]

gems: [jekyll-paginate, jekyll-seo-tag]
